### ISSUE TITLE
RST table not showing up on package README

### ISSUE THREAD

**Issue by chapulina** [ros-infrastructure/rosindex#111]
But it works for the documentation generated with Sphinx.

See for example how the exact same table works as a documentation page, but not as a package README:

* [Working source code](https://github.com/ros2/ros2_documentation/blame/master/Managed-Nodes.rst#L71)
* [Working rendered table](https://index.ros.org/doc/ros2/Managed-Nodes/#run-the-demo)

* [Failing source code](https://github.com/ros2/demos/blame/bouncy/lifecycle/README.rst#L80) - which is a copy of the working code
* [Failing rendered table](https://index.ros.org/p/lifecycle/github-ros2-demos/#bouncy) - it's just not there

CC @Karsten1987

**Comment by hidmic** [comment]
So, the thing here is that we're not processing both package READMEs and documentation pages the same way. The latter are processed using Sphinx, the former is an older implementation that uses Pandoc to convert RST files into its Markdown "equivalent" before feeding it Jekyll. I presume the conversion step is the culprit.

**Comment by apojomovsky** [comment]
I can confirm this issue gets solved by using a recent version of Pandoc, given that the version installed by Ubuntu 16 is quite old and doesn't include support for list-tables (like the one from the failing example) while processing RST files.
I'm working on updating the Dockerfile so that we get the right version of Pandoc.
