### ISSUE TITLE
list of all packages known to ros index with their licenses

### ISSUE THREAD

**Issue by flynneva** [ros-infrastructure/rosindex#181]
each package right now known to the index also has its license known. it would be cool to export this list of packages as a csv or something similar with their licenses attached. useful for any business considering switching over to ROS2 and floating it by their legal department.

**Comment by dirk-thomas** [comment]
I don't think this feature is in the scope of this repo / index.ros.org. You should be able to collect the same information using a simple Python script using the `rosdistro` API. Just a few pointers for this:

* `import rosdistro`
* `index = rosdistro.get_index(rosdistro.get_index_url())`
* `dist = rosdistro.get_distribution(index, 'distro_name')`
* loop over `dist.release_packages.keys()`

  * `xml = dist.get_release_package_xml(pkg_name)`
  * `import catkin_pkg.package`
  * `pkg = catkin_pkg.package.parse_package_string(xml)`
  * a `pkg` has a `licenses` attribute with the information from the manifest

I hope this help to get the information you like. I will go ahead and close this ticket since I don't think it is something we will add to index.ros.org.

**Comment by flynneva** [comment]
for anyone else who is looking for something like this....

```bash
pip install rosdistro
```
and then....
```python
#!/usr/bin/env python3

import rosdistro
import catkin_pkg.package
import csv

dist_name = "eloquent"

index = rosdistro.get_index(rosdistro.get_index_url())
dist = rosdistro.get_distribution(index, dist_name)

with open(dist_name + "_package_licenses.csv", mode='w') as pkg_license_file:
  csv_writer = csv.writer(pkg_license_file, delimiter=',',quotechar='"', quoting=csv.QUOTE_MINIMAL)
  for pkg_name in dist.release_packages.keys():
      try:
        xml = dist.get_release_package_xml(pkg_name)
        pkg = catkin_pkg.package.parse_package_string(xml)
        for lic in pkg.licenses:
          csv_writer.writerow([pkg_name, lic])
          print(pkg_name + ": " + lic)
      except:
          csv_writer.writerow([pkg_name, "license not found"])
          print("could not get license for " + pkg_name)
```
