### ISSUE TITLE
Missing catkin_pkg during installation of ros2 crystal on Ubuntu 18.04

### ISSUE THREAD

**Issue by toshiharutf** [ros-infrastructure/rosindex#247]
I was trying to build ros2 crystal following the instructions on https://index.ros.org/doc/ros2/Installation/Crystal/Linux-Development-Setup/  but I run into a problem with catkin_ament . It seems that the catkin_pkg was missing. 

I solved it by installing the package manually on my env. I don't now if other users run into the same problem, but I would hurt adding this pkg to intallation list:

python3 -m pip install catkin_pkg

Best regards

**Comment by tfoote** [comment]
Please open a ticket on ros2_documentation where this content is hosted: https://github.com/ros2/ros2_documentation/issues/new

Please be a little bit more specific about what your problem is catkin_ament is not a think that I'mfamiliar with so please point to the specific command you're having trouble running. https://github.com/ros2/ros2_documentation/blob/master/source/Installation/Crystal/Linux-Development-Setup.rst
