### ISSUE TITLE
Broken Link: ros2 brouchure

### ISSUE THREAD

**Issue by auman66** [ros-infrastructure/rosindex#259]
https://index.ros.org/doc/ros2/_downloads/ca487a5e252ef6910bcb40402640bde6/ros2-brochure-a4-web.pdf

**Comment by clalancette** [comment]
So the issue here is that we transitioned everything over from https://index.ros.org to https://docs.ros.org : https://discourse.ros.org/t/index-ros-org-doc-ros2-is-being-retired/19141 .

Due to technical limitations, the way we had to do it is with http-equiv redirects, and that only works with html pages.

I've opened up https://github.com/ros2/ros2_documentation/pull/1186 which would fix this.

**Comment by tfoote** [comment]
fixed in https://github.com/ros2/ros2_documentation/pull/1186
