### ISSUE TITLE
Broken Link: https://github.com/PX4/px4_msgs

### ISSUE THREAD

**Issue by naufiero** [ros-infrastructure/rosindex#279]

**Comment by clalancette** [comment]
That link seems to work fine for me.  Can you please point out where you were following that from?

**Comment by naufiero** [comment]
It was actually the link: https://index.ros.org/doc/ros2/Tutorials/Ament-Tutorial/ under "Amen tutorial,"
Which is in the readme for the link above.

**Comment by clalancette** [comment]
OK, thanks.  In that case, please open up an issue over at https://github.com/PX4/px4_msgs, saying that the tutorial has moved to https://docs.ros.org/en/rolling/Tutorials/Custom-ROS2-Interfaces.html , and the README there should be updated.

Since this isn't a bug in rosindex itself, I'm going to go ahead and close this.
