### ISSUE TITLE
Broken Link: 

### ISSUE THREAD

**Issue by Schelbert197** [ros-infrastructure/rosindex#339]
https://index.ros.org/p/swiftnav_piksi

While looking for information on this package for ros2

**Comment by tfoote** [comment]
This package isn't released on any platform so it's not in the index

I assume you found it from: https://wiki.ros.org/swiftnav_piksi which has a speculative link to the package page, but since that isn't a package it's an invalid link

```
Note: This page is obsolete.

See the [swiftnav_ros](http://wiki.ros.org/swiftnav_ros) page, which is maintained by Swiftnav, for updated information on piksi and piksi multi. This page is retained for historical purposes during the transition to the Swiftnav-maintained page, and may be deleted in the future.
```

For good measure I've removed the invalid header. https://wiki.ros.org/action/diff/swiftnav_piksi?action=diff&rev1=32&rev2=33
