### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system

### ISSUE THREAD

**Issue by choatej** [ros-infrastructure/rosindex#369]
### 404 Page URL

https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system

### Referrer URL

none

### Description

link was logged:
[spawn_entity.py-3] ModuleNotFoundError: No module named 'rclpy._rclpy_pybind11'
[spawn_entity.py-3] The C extension '/opt/ros/galactic/lib/python3.8/site-packages/_rclpy_pybind11.cpython-312-x86_64-linux-gnu.so' isn't present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system' for possible solutions
The only part of the link that is valid is index.ros.org/

**Comment by CursedRock17** [comment]
While Galactic is End of LIfe, this was the link it should've taken you to: https://docs.ros.org/en/galactic/How-To-Guides/Installation-Troubleshooting.html. Scroll down to the second section and the answer will lie there, but this should've been fixed by [this pull request](https://github.com/RoboStack/ros-galactic/issues/96). Otherwise, using a newer version like Iron or Humble should have this issue fixed.

**Comment by clalancette** [comment]
Yes, because this is from an EOL distro, I'm going to go ahead and close this one.
