### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Concepts

### ISSUE THREAD

**Issue by kjhann** [ros-infrastructure/rosindex#371]
### 404 Page URL

https://index.ros.org/doc/ros2/Concepts

### Referrer URL

https://ubuntu.com/tutorials/getting-started-with-ros-2#1-overview

### Description

in the what you'll learn paragraph in the overview of getting started with ROS the link attached to the text "ROS 2 tutorials"

**Comment by CursedRock17** [comment]
I don't believe that Ubuntu wanted to link over to `ROSIndex`, I believe - using the context of the paragraph - they wanted to link to: https://docs.ros.org/en/foxy/Concepts.html. That concepts sections in the ROS 2 Foxy (which is version that is EOL) Docs would be more valuable in your devolpment with ROS 2, that or the official [Tutorials Section](https://docs.ros.org/en/foxy/Tutorials.html). Though, since Foxy is End-Of-Life, I would recommend using a more recent [version](https://docs.ros.org/en/foxy/Releases.html) like Humble or Iron

**Comment by clalancette** [comment]
It looks like this was reported more than a year ago: https://discourse.ubuntu.com/t/getting-started-with-ros-2/17847/4 .  Still needs an update on the source page.

**Comment by tfoote** [comment]
Since there's feedback upstream, closing this here.
