### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Installation

### ISSUE THREAD

**Issue by ProtoDolph** [ros-infrastructure/rosindex#385]
### 404 Page URL

https://index.ros.org/doc/ros2/Installation

### Referrer URL

https://github.com/ros2-java/ros2_java/blob/main/README.md

### Description

the page doesn't exist any more

**Comment by CursedRock17** [comment]
I've added an issue for the link to get fixed with the correct link that you're looking for, so @ProtoDolph if you head over to that issue you'll be redirected to the correct installation process for the `rolling` distribution, here's the [galatic distribution ](https://docs.ros.org/en/galactic/index.html) too, though it's EOL. That being said, I don't know if this information will be merged over since the repo hasn't been updated in 2 years, so we can proceed with the issue here however we feel best.

**Comment by tfoote** [comment]
I opened a PR on that repo to fix the link. https://github.com/ros2-java/ros2_java/pull/246

Closing this as we don't have power over that link.
