### ISSUE TITLE
Index ROS (1) distros

### ISSUE THREAD

**Issue by hidmic** [ros-infrastructure/rosindex#43]
We're currently indexing ROS 2 distros only. It'd be nice for rosindex to show the whole ROS* ecosystem.

**Comment by hidmic** [comment]
AFAIK this is a non-trivial task. At the very least, packages instances need further qualification, as they may belong to ROS, ROS2 or both (e.g. a migration).

But it'd be nice :)

**Comment by tfoote** [comment]
The instances will all have unique rosdistro names so that shouldn't be a problem. I think the only limiting factor is that the config needs to take multiple rosdistro paths: https://github.com/ros2/rosindex/blob/8baf3254b0749a08ef9d5286548ee84b9180936c/_config.yml#L84 since we currently have ROS1 and ROS2 in different repos.

**Comment by hidmic** [comment]
Great then! I didn't know we could rely on distro name uniqueness :).

**Comment by tfoote** [comment]
btw this is currently deployed to https://ros-infrastructure.github.io/index.ros.org/ for testing

**Comment by hidmic** [comment]
Done in #54. Closing this one.
