### ISSUE TITLE
Cross-reference rosdeps and packages

### ISSUE THREAD

**Issue by hidmic** [ros-infrastructure/rosindex#44]
While package pages do list rosdep system dependencies, back-references are yet to be implemented. We'd like to have them available as well.

**Comment by hidmic** [comment]
@tfoote @apojomovsky I need some feedback here guys. I started drafting this one. Getting the back-references is easy, showing them not so much. Conceptually it's another package list, filtered by rosdep usage. But:

- The current package list, as well as the package instance list per package, is generated statically (even pagination is static). It's somewhat easy to extend but going down that same route for package usage may not scale that well. Imagine that, on average, we have N system deps with M dependant packages each, in each one of the K distros. In turn, each package carries P instances that apply for the filter (i.e. some instance of some package in some distro may or may not require some system dependency). Then suppose that we get to put Q packages per distro specific list. That's `N*ceil(M/Q)*K+N*M*P*K` new static pages.

- An alternative is to reuse our lunr.js search index and filter package lists per request, which I think scales better (assuming we want to keep `lunr.js` and that it scales well as a poor man's DB).

The former seems more natural but we're going to go past 100K files easily (we're at 6.5K right now). What do you think?

**Comment by tfoote** [comment]
Because rosdeps are system wide I don't think we need the full complexity for each one and should only use  the existing single page per rosdep and that can hold all the back references. For example https://ros-infrastructure.github.io/index.ros.org/d/eigen/

At the bottom we can just fill in the section "used in packages" with sections per rosdistro and list all packages that use the dependency. 
```
Used in Packages

- Kinetic
  - foo
  - bar
  - baz

- Bouncy
  - foo
  - baz
  - foobar
```
This was outline for for convenience but we could just have them be a tag field or list in a separate div.

We should be able to statically generate this at build time and we just have to add the extra links here.

**Comment by hidmic** [comment]
Hmm, ok. So what you say is: no distro switch, packages listed per distro if at least one instance in that distro has the dependency and a long page if the whole list happens to be a bit long :). Is that right? I was hoping to reuse list layouts, but I'm fine with a simpler approach.

**Comment by tfoote** [comment]
Yeah, a long page is fine. We can also do a list like this with multiple items per line.

![image](https://user-images.githubusercontent.com/447804/45909824-1abd1980-bdb9-11e8-9457-570305a6b1cc.png)

to keep the page from getting too long.
